config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  get 'pump/pump_status'
  get 'pump/set_pump_status'
  
  resources :measures do
    collection do
      get 'remove_all'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'measures#index'

  namespace :charts do
    get "hour_temp_out"
    get "hour_temp_in"
    get "week_temp_out"
    get "week_temp_in"
    get "hour_humidity_out"
    get "hour_humidity_in"
    get "week_humidity_out"
    get "week_humidity_in"
  end
  
end

app/models/measure.rb
class Measure < ApplicationRecord

    scope :recent, -> {where('created_at >= :thirty_six_hours_ago', thirty_six_hours_ago: Time.now - 36.hours)}

    def self.temp_by_time

        find_by_sql(<<-SQL
            SELECT
            #date_trunc('minute', created_at) AS date_time,
            date_trunc('minute', created_at),    
            temp_out,
            temp_in
            FROM measures
            GROUP BY created_at, temp_out, temp_in
            ORDER BY created_at
            SQL
          ).map do |row|
            [
                row['date_time'],
                row.temp_out,
                row.temp_in,
            ]
          end
    end

end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController
  before_action :set_measure, only: [:show, :edit, :update, :destroy]
  # GET /measures
  # GET /measures.json
  def index

    require 'net/http'
    require 'json'

    @measures = Measure.all.order("created_at DESC")
    weatherData

  end

  # GET /measures/1
  # GET /measures/1.json
  def show
  end

  # GET /measures/new
  def new
    @measure = Measure.new
  end

  # GET /measures/1/edit
  def edit
  end

  # POST /measures
  # POST /measures.json
  # Recieve data from Arduino and save in database
  def create
    @measure = Measure.new(measure_params)
    logger.debug "New Measure: #{@measure.attributes.inspect}"
    respond_to do |format|
      if @measure.save
        format.html { redirect_to @measure, notice: 'Measure was successfully created.' }
        format.json { render :show, status: :created, location: @measure }
        MeasureCleanupJob.set(wait: 36.hours).perform_later @measure
      else
        format.html { render :new }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
    @@pumpStatus = "|" + measure_params[:pump_status].to_s + "|"
    logger.debug "@@pumpStatus has been set to:  #{@@pumpStatus}"
  end

  # PATCH/PUT /measures/1
  # PATCH/PUT /measures/1.json
  def update
    respond_to do |format|
      if @measure.update(measure_params)
        format.html { redirect_to @measure, notice: 'Measure was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure }
      else
        format.html { render :edit }
        format.json { render json: @measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measures/1
  # DELETE /measures/1.json
  def destroy
    @measure.destroy
    respond_to do |format|
      format.html { redirect_to measures_url, notice: 'Measure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Remove all table entries 
  # Use for development purposes.
  #GET /measures/remove_all
  def remove_all
    Measure.delete_all
    flash[:notice] = "You have removed all measurements!"
    redirect_to measures_path
  end

  def pumpStatus
    @@pumpStatus
  end

  helper_method :pumpStatus

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure
      @measure = Measure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_params
      params.require(:measure).permit(:temp_out, :temp_in, :humidity_out, :humidity_in, :pump_status)
    end

    def setOnline(state)
      @online = state
    end

    # Method call and processes the DarkSky API to produc local westher forcast
    # Selects teh correct icon to be displayed
    def weatherData 

      icons = {
        "clear-day" => "pe-7w-sun",
        "clear-night" => "pe-7w-moon",
        "rain" => "pe-7w-rain-alt",
        "snow" => "pe-7w-snow-alt",
        "sleet" => "pe-7w-snow",
        "wind" => "pe-7w-wind",
        "fog" => "pe-7w-fog",
        "cloudy" => "pe-7w-cloud",
        "partly-cloudy-day" => "pe-7w-cloud-sun",
        "partly-cloudy-night" => "pe-7w-cloud-moon", 
        "default" => "pe-7w-thermometer-full",
      }
      
      @weather_data = HTTParty.get('https://api.darksky.net/forecast/f3d5dcb788b60bc988305e4ba4bf0fe9/51.208168,-1.516628?exclude=hourly,minutely,flags&units=auto')

    # Current Weather
      @current_time = Time.at(@weather_data ['currently']['time'].to_i)
      @timezone = @weather_data ['timezone']
      @current_summary = @weather_data ['currently']['summary']
      
      @current_icon = icons.fetch(@weather_data ['currently']['icon'],"pe-7w-thermometer-full")
      @current_temp = @weather_data ['currently']['temperature'].to_i
      @current_temp_feels = @weather_data ['currently']['apparentTemperature'].to_i
      @current_humidity = (@weather_data ['currently']['humidity'] * 100).to_i
      @current_windspeed = @weather_data ['currently']['windSpeed'].to_i
      @current_windgust = @weather_data ['currently']['windGust'].to_i
      @current_windbearing = @weather_data ['currently']['windBearing']
      @current_cloudcover = (@weather_data ['currently']['cloudCover'] * 100).to_i
      @current_uvindex = @weather_data ['currently']['uvIndex']
      if @current_uvindex <= 2
        @uvindex = 'bg-succes'
      elsif @current_uvindex <= 5
        @uvindex = 'bg-yellow'
      elsif @current_uvindex <= 7
        @uvindex = 'bg-warning'
      elsif @current_uvindex <= 10
        @uvindex = 'bg-danger'
      elsif @current_uvindex < 10
        @uvindex = 'bg-violet'
      else 
        @uvindex = 'bg-transparent'
      end
      @current_percp = (@weather_data ['currently']['precipProbability'] * 100).to_i
      @current_high = @weather_data ['daily']['data'][0]['temperatureHigh']
      @current_low = @weather_data ['daily']['data'][0]['temperatureLow']
      
      #weather forcast
      @weekly_summary = @weather_data ['daily']['summary']
      # Next 6 days
      @day_one_time = Time.at( @weather_data ['daily']['data'][1]['time'].to_i)
      @day_one_icon = icons [@weather_data ['daily']['data'][1]['icon']]
      @day_one_hi = @weather_data ['daily']['data'][1]['temperatureHigh'].to_i
      @day_one_low = @weather_data ['daily']['data'][1]['temperatureLow'].to_i

      @day_two_time = Time.at( @weather_data ['daily']['data'][2]['time'].to_i)
      @day_two_icon = icons [@weather_data ['daily']['data'][2]['icon']]
      @day_two_hi = @weather_data ['daily']['data'][2]['temperatureHigh'].to_i
      @day_two_low = @weather_data ['daily']['data'][2]['temperatureLow'].to_i

      @day_three_time = Time.at( @weather_data ['daily']['data'][3]['time'].to_i)
      @day_three_icon = icons [@weather_data ['daily']['data'][3]['icon']]
      @day_three_hi = @weather_data ['daily']['data'][3]['temperatureHigh'].to_i
      @day_three_low = @weather_data ['daily']['data'][3]['temperatureLow'].to_i

      @day_four_time = Time.at( @weather_data ['daily']['data'][4]['time'].to_i)
      @day_four_icon = icons [@weather_data ['daily']['data'][4]['icon']]
      @day_four_hi = @weather_data ['daily']['data'][4]['temperatureHigh'].to_i
      @day_four_low = @weather_data ['daily']['data'][4]['temperatureLow'].to_i

      @day_five_time = Time.at( @weather_data ['daily']['data'][5]['time'].to_i)
      @day_five_icon = icons [@weather_data ['daily']['data'][5]['icon']]
      @day_five_hi = @weather_data ['daily']['data'][5]['temperatureHigh'].to_i
      @day_five_low = @weather_data ['daily']['data'][5]['temperatureLow'].to_i

      @day_six_time = Time.at( @weather_data ['daily']['data'][6]['time'].to_i)
      @day_six_icon = icons [@weather_data ['daily']['data'][6]['icon']]
      @day_six_hi = @weather_data ['daily']['data'][6]['temperatureHigh'].to_i
      @day_six_low = @weather_data ['daily']['data'][6]['temperatureLow'].to_i

    end

end

app/helpers/measures_helper.rb
module MeasuresHelper
end

app/views/measures/_form.html.erb
<%= form_with(model: measure, local: true) do |form| %>
  <% if measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(measure.errors.count, "error") %> prohibited this measure from being saved:</h2>

      <ul>
      <% measure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :temp_out %>
    <%= form.text_field :temp_out %>
  </div>

  <div class="field">
    <%= form.label :temp_in %>
    <%= form.text_field :temp_in %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/measures/edit.html.erb
<h1>Editing Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Show', @measure %> |
<%= link_to 'Back', measures_path %>

app/views/measures/index.html.erb
<div class='container'>
<h6 class='text-center'><%= @online%></h6>
  <h2 class='p-3 text-center'> Garden Live Data </h2>

  <div id='latest_data' class="jumbotron p-1 p-md-5 text-center text-white rounded bg-secondary">
    <h3 class='mb-4'>Watering System</h3>
    <h4 class='mb-4'>Current Pump status: <%=pumpStatus == "|0|" ? "OFF" : "ON"%></h4>
    <div class='row'>
          <div class = 'col-md-4'>
            <%= link_to 'Garden & Green House', pump_set_pump_status_path(:status => "|1|"), class: 'btn btn-lg btn-block btn-outline-success' %>
            <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Garden pots (not including raised beds) will be watered for 5mins followed by the Green House for a further 5mins.</p>
          </div>
          <div class = 'col-md-4'>
            <%= link_to 'Green House', pump_set_pump_status_path(:status => "|2|"), class: 'btn btn-lg btn-block btn-outline-success' %>
            <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Water the Green House only for 5mins.</p>
          </div>
          <div class = 'col-md-4'>
            <%= link_to 'Stop Watering', pump_set_pump_status_path(:status => "|0|"), class: 'btn btn-lg btn-block btn-outline-danger' %>
            <p class = 'my-0 pl-0 py-2 text-center text-md-left'> Watering stops automatically - but just incase.......</p>
          </div>
    </div> <!-- row -->
  </div>

  <div id='latest_data' class="jumbotron p-1 p-md-5 text-center rounded bg-light">
    <h3 class='mb-4'>Local Current & Forecasted Weather</h3>
    
    <div class='row'> 
      <div class = 'col-md-4'>
        <h5 class = 'mx-auto my-auto'><i class='<%=@current_icon%> icon-lg'></i></h5>
        <h5 class = 'mx-auto my-auto'> <%=@current_time.strftime("%a %d %b %y")%></h5>
        <p><%=@timezone%></p>
      </div>
      <div class = 'col-md-8'>
        <div id='latest_data' class="jumbotron py-1 text-center rounded">
            <h5 class = 'mx-auto'>Current conditions: <em class='font-weight-light'><%=@current_summary%></em></h5>
    
            <div class ='row border-top'>
              <div class = 'col-md-1 d-none d-md-block'>
                <span class='mx-auto px-3 pe-7w-thermometer-full icon-xs'></span>
              </div>
              <div class = 'col-md-5'>
                <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Temperature: <%= @current_temp%>&#8451;</p>
              </div>
              <div class = 'col-md-1 d-none d-md-block'>
                <span class='mx-auto px-3 pe-7w-thermometer-1-4 icon-xs'>  </span>
              </div>  
              <div class = 'col-md-5'>
                <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Feels like: <%= @current_temp_feels%>&#8451;</p>
              </div>
            </div><!-- row -->

            <div class ='row border-top'>
              <div class = 'col-md-1 d-none d-md-block'>
                <span class='mx-auto px-1 pe-7w-umbrella icon-xs'></span>
              </div>
              <div class = 'col-md-5'>
                <p class = 'my-0 pl-0 py-2 text-center text-md-left'><%=@current_percp%>&#37; chance of rain</p>
              </div>
              <div class = 'col-md-1 d-none d-md-block'>
                <span class='my-0 px-1 pe-7w-cloud-sun icon-xs'></span>
              </div>
              <div class = 'col-md-5'>
                <p class = 'my-0 pl-0 py-2 text-center text-md-left'><%=@current_humidity%>&#37; Humidity</p>
              </div>
            </div><!-- row -->
            <div class ='row border-top'>
                <div class = 'col-md-1 d-none d-md-block'>
                  <span class='mx-auto px-1 pe-7w-sun icon-xs'></span>
                </div>
                <div class = 'col-md-5'>
                  <p class = 'my-0 pl-0 py-2 text-center text-md-left'>UV Index: <span class = 'px-2 border rounded-circle w-25 <%=@uvindex%>'> <%=@current_uvindex%> </span></p>
                </div>
                <div class = 'col-md-1 d-none d-md-block'>
                  <span class='mx-auto px-1 pe-7w-cloud icon-xs'></span>
                </div>
                <div class = 'col-md-5'>
                  <p class = 'my-0 pl-0 py-2 text-center text-md-left'><%=@current_cloudcover%>&#37; Cloud Cover</p>
                </div>
            </div><!-- row -->
            <div class ='row border-top'>
              <div class = 'col-md-2 d-none d-md-block'>
                <span class='mx-auto px-1 pe-7w-wind icon-xs'></span>
              </div>
              <div class = 'col-md-10'>
                <p class = 'my-0 py-2 text-center text-md-left'>Wind Speed: <%=@current_windspeed%>mph</p>
              </div>
            </div><!-- row -->
            <div class ='row'>
              <div class = 'col-md-2 d-none d-md-block'>
                <span class='mx-auto px-1 pe-7w-wind icon-xs'></span>
              </div>
              <div class = 'col-md-10'>
                <p class = 'my-0 py-2 text-center text-md-left'>Wind Gusts: <%=@current_windgust%>mph</p>
              </div>
            </div><!-- row -->
        </div> <!-- jumbotron -->
      </div>
    </div>
    
    <div class='row'>
    	<h5 class = 'mx-auto'>Weekly forecast: <em class='font-weight-light'><%=@weekly_summary%></em></h5>
    </div>

    <div class='row'> 
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_one_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_one_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_one_low%>&#8451;</p>
          <h5> <%=@day_one_time.strftime("%a")%></h5>
        </div>
      </div>
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_two_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_two_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_two_low%>&#8451;</p>
          <h5> <%=@day_two_time.strftime("%a")%></h5>
        </div>
      </div>
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_three_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_three_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_three_low%>&#8451;</p>
          <h5> <%=@day_three_time.strftime("%a")%></h5>
        </div>
      </div>
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_four_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_four_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_four_low%>&#8451;</p>
          <h5> <%=@day_four_time.strftime("%a")%></h5>
        </div>
      </div>
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_five_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_five_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_five_low%>&#8451;</p>
          <h5> <%=@day_five_time.strftime("%a")%></h5>
        </div>
      </div>
      <div class = 'col-md-2 col-xs-1'>
        <div class = 'jumbotron p-1 text-center rounded border'>
          <i class='<%=@day_six_icon%> icon-sm'></i>
          <p class = 'my-0 text-center'>Hi: <%=@day_six_hi%>&#8451;</p>
          <p class = 'my-0 text-center'>Low: <%=@day_six_low%>&#8451;</p>
          <h5> <%=@day_six_time.strftime("%a")%></h5>
        </div>
      </div> 
    </div>
    <p class = 'text-muted my-0 text-center'> <em>Last Updated on </em> <%=@current_time.strftime("%d %b %y @ %k:%M ")%></p> 
    <p class = 'text-muted p-0 m-0'>Powered by <a href='https://www.darksky.net'>Darksky</a></p>
  </div>

    <div id='latest_data' class="jumbotron p-1 p-md-5 text-center text-white rounded bg-secondary">
    <h3 class='mb-4'>Live Conditions</h3>
    <% unless @measures[0].nil? %>
      <div class='row border-bottom'>
        <div class = 'col'> 
          <h5 class = 'mx-auto'><em>Live</em> Garden Conditions</h5>
        </div>
      </div><!--row -->

      <div class ='row pb-3'>
        <div class = 'col-md-1 d-none d-md-block'>
          <span class='mx-auto px-3 pe-7w-thermometer-full icon-xs'></span>
        </div>
        <div class = 'col-md-5'>
          <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Outside Air Temperature:   <%=@measures[0].temp_out%>&#8451;</p>
        </div>
        <div class = 'col-md-1 d-none d-md-block'>
          <span class='mx-auto px-3 pe-7w-cloud-sun icon-xs'>  </span>
        </div>  
        <div class = 'col-md-5'>
          <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Humidity:  <%=@measures[0].humidity_out%>%</p>
        </div>
      </div><!-- row -->
    <div class = 'row border-bottom'>
    <div class = 'col'>
          <h5 class = 'mx-auto'><em>Live</em> Green House Conditions</h5>
        </div>
    </div>
      <div class ='row'>
        <div class = 'col-md-1 d-none d-md-block'>
          <span class='mx-auto px-3 pe-7w-thermometer-full icon-xs'></span>
        </div>
        <div class = 'col-md-5'>
          <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Green House Air Temperature:   <%=@measures[0].temp_in%>&#8451;</p>
        </div>
        <div class = 'col-md-1 d-none d-md-block'>
          <span class='mx-auto px-3 pe-7w-cloud-sun icon-xs'>  </span>
        </div>  
        <div class = 'col-md-5'>
          <p class = 'my-0 pl-0 py-2 text-center text-md-left'>Humidity:  <%=@measures[0].humidity_in%>%</p>
        </div>
      </div><!-- row -->
  
      <p class = 'text-center'>Last Updated: <%=@measures[0].created_at.strftime("%d %b %y @ %k:%M ")%> </p> 
      
      
    <% end %>
    
  </div>


  <!--<%= line_chart charts_hour_temp_out_path, refresh: 60, xtitle: "Time", ytitle: "Temperature", messages:{empty: "Sorry.... No Data Yet!"}%>
  <%= line_chart charts_hour_temp_in_path, refresh: 60, xtitle: "Time", ytitle: "Temperature", messages:{empty: "Sorry.... No Data Yet!"}%>
  <%= line_chart charts_hour_humidity_out_path, refresh: 60, xtitle: "Time", ytitle: "Humidity", suffix: "%", messages:{empty: "Sorry.... No Data Yet!"}%>
  <%= line_chart charts_hour_humidity_in_path, refresh: 60, xtitle: "Time", ytitle: "Humidity", suffix: "%", messages:{empty: "Sorry.... No Data Yet!"}%>-->

  <!--p><%= @measures.size %>
  <%= link_to 'Remove All', remove_all_measures_path, class: 'btn btn-sm btn-outline-danger' %>
  <% @measures.each do |measure|%>
    <div class = 'list-group-item list-group-item-action'>
      
        <div class='row'>
          <div class='col-2 '><%=measure.created_at.strftime("%d %b %y @ %k:%M ")%></div>
          <div class='col-2'><%= measure.temp_out%></div>
          <div class='col-2'><%= measure.temp_in%></div>
          <div class='col-2'><%= measure.pump_status%></div>
        </div>
      
    </div>
  <%end%> -->

app/views/measures/new.html.erb
<h1>New Measure</h1>

<%= render 'form', measure: @measure %>

<%= link_to 'Back', measures_path %>

app/views/measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temp out:</strong>
  <%= @measure.temp_out %>
</p>

<p>
  <strong>Temp in:</strong>
  <%= @measure.temp_in %>
</p>

<%= link_to 'Edit', edit_measure_path(@measure) %> |
<%= link_to 'Back', measures_path %>